version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  assignees:
  - LaserFlash
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.0.2
    - 2.1.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 1.2.0
    - 2.0.2
  - dependency-name: "@angular/material"
    versions:
    - 11.2.6
  - dependency-name: "@angular/compiler-cli"
    versions:
    - 11.2.7
  - dependency-name: karma
    versions:
    - 6.3.0
    - 6.3.2
  - dependency-name: "@angular/core"
    versions:
    - 11.2.7
  - dependency-name: "@angular/common"
    versions:
    - 11.2.7
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.2.7
  - dependency-name: "@angular/forms"
    versions:
    - 11.2.7
  - dependency-name: "@angular/router"
    versions:
    - 11.2.7
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 1.2.0
    - 2.0.2
  - dependency-name: "@angular-eslint/schematics"
    versions:
    - 2.0.1
    - 2.0.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.4
    - 0.1102.6
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.22.0
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.0.1
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.2
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 32.3.2
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.9
