language: node_js
node_js:
   - '10'

cache:
  directories:
  - node_modules

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  target_branch: master
  fqdn: laserflash.tk
  github_token: $GITHUB_TOKEN
  email: bryn.t.bennett@gmail.com
  name: Bryn Bennett
  on:
    branch: master
